const START=new Date('2026-07-14T00:00:00-03:00');
const intro=document.getElementById('intro'),site=document.getElementById('site');
document.getElementById('enterBtn').addEventListener('click',()=>{intro.style.transition='opacity .9s ease,transform .9s ease';intro.style.opacity='0';intro.style.transform='scale(1.03)';setTimeout(()=>{intro.remove();site.classList.remove('hidden');observeReveals();},850)});
function pad(n){return String(n).padStart(2,'0')}
function updateCounter(){let now=new Date(),total=Math.max(0,now-START);let months=(now.getFullYear()-START.getFullYear())*12+(now.getMonth()-START.getMonth());if(now.getDate()<START.getDate())months--;let anchor=new Date(START);anchor.setMonth(anchor.getMonth()+Math.max(months,0));let rem=Math.max(0,now-anchor),days=Math.floor(rem/86400000);rem%=86400000;let hours=Math.floor(rem/3600000);rem%=3600000;let minutes=Math.floor(rem/60000);let seconds=Math.floor((rem%60000)/1000);document.getElementById('months').textContent=pad(Math.max(0,months));document.getElementById('days').textContent=pad(days);document.getElementById('hours').textContent=pad(hours);document.getElementById('minutes').textContent=pad(minutes);document.getElementById('seconds').textContent=pad(seconds)}
setInterval(updateCounter,1000);updateCounter();
function observeReveals(){const els=document.querySelectorAll('.reveal');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>obs.observe(e))}observeReveals();
const modal=document.getElementById('modal'),title=document.getElementById('modalTitle'),text=document.getElementById('modalText');const modalTexts={'Seu jeito de cuidar':'tem um jeito seu de cuidar de mim que aparece até nas coisas pequenas. talvez você nem perceba, mas eu percebo.','A sua risada':'é impossível não sorrir quando você começa a rir de verdade. e eu gosto ainda mais quando sou eu que causei isso.','As nossas conversas':'eu gosto de como a gente consegue conversar sobre qualquer coisa e, quando vê, já passou horas.','Até a sua agonia':'sim, até isso. porque provocar você e ver sua reação já virou uma das minhas diversões favoritas.'};document.querySelectorAll('.detail-card').forEach(b=>b.addEventListener('click',()=>{title.textContent=b.dataset.modal;text.textContent=modalTexts[b.dataset.modal];modal.classList.add('open');modal.setAttribute('aria-hidden','false')}));
document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
const lm=document.getElementById('letterModal'),letterBtn=document.getElementById('letterBtn');letterBtn.onclick=()=>{if(!letterBtn.classList.contains('open')){letterBtn.classList.add('open');setTimeout(()=>{lm.classList.add('open');lm.setAttribute('aria-hidden','false')},850)}else{lm.classList.add('open');lm.setAttribute('aria-hidden','false')}};document.getElementById('closeLetter').onclick=()=>{lm.classList.remove('open');setTimeout(()=>letterBtn.classList.remove('open'),350)};lm.addEventListener('click',e=>{if(e.target===lm){lm.classList.remove('open');setTimeout(()=>letterBtn.classList.remove('open'),350)}});
const result=document.getElementById('quizResult');document.querySelectorAll('.quiz-options button').forEach(b=>b.onclick=()=>{result.textContent=b.dataset.correct==='true'?'acertou. mas eu espero que você já soubesse disso ♡':'quase... mas você ainda tem dois meses para descobrir.'});
const musicPanel=document.getElementById('musicPanel');document.getElementById('musicBtn').onclick=()=>musicPanel.classList.toggle('open');document.getElementById('closeMusic').onclick=()=>musicPanel.classList.remove('open');
document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('open');lm.classList.remove('open');musicPanel.classList.remove('open');setTimeout(()=>letterBtn.classList.remove('open'),350)}});
